### PR TITLE
Add overture data script

### PR DESCRIPTION
**Pull request by giswqs**

### CODE REVIEW

**Comment by spicysardine** [comment]
Hy

url link is broken:

Adding addresses data...
Failed to open addresses data.
Adding base data...
Failed to open base data.
Adding buildings data...
Failed to open buildings data.
Adding divisions data...
Failed to open divisions data.
Adding transportation data...
Failed to open transportation data.
Done!

Following the style link:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>FC12ZVKJ8RHKZGW4</RequestId>
<HostId>
zarX8Xlds20Sp8FwWr6WoVLxZj+WlVoyK6K909gQY49ZYWgeV66Ay+QKBeqYzohnwpL8lmhknvE=
</HostId>
</Error>

**Comment by giswqs** [comment]
What QGIS and GDAL versions do you have? You may need to update QGIS to the latest everion and at least GDAL 3.8 to use this.

**Comment by giswqs** [comment]
Works fine on my QGIS 3.38.2 + GDAL 3.9.2

```python
from osgeo import gdal
print(gdal.__version__)
```

image

**Comment by spicysardine** [comment]
It should not be the case IMO:
Production machines use long term stable  releases (LTS).
The feature itself is interesting for its global reach and out of site storage, otherwise you can do the same locally with geofabrik (which is most likely its data source).
In other words I do not think you need bleeding edge versions of OGR to load a web map vector feature like this one;
so a bit of retro-compatibility (nothing pre-historical though ;) could be appreciated.

**Comment by giswqs** [comment]
QGIS may not be the key issue here, but GDAL definitely is. I think GDAL only added support for PMTiles in 3.8. Run the following in your QGIS Python console to see what GDAL version you have 

```python
from osgeo import gdal
print(gdal.__version__)
```

**Comment by giswqs** [comment]
See https://gdal.org/en/latest/drivers/vector/pmtiles.html

**Comment by spicysardine** [comment]
I know my GDAL/OGR version its less than 3.8

an ogrinfo on the url gives:

```
Unable to open datasource `/vsicurl/https://overturemaps-tiles-us-west-2-beta.s3.amazonaws.com/2024-09-18/buildings.pmtiles' with the following drivers.
  -> ESRIC
  -> FITS
  -> PCIDSK
  -> netCDF
  -> PDS4
  -> VICAR
  -> JP2OpenJPEG
```
So short answer is: nothing to do just upgrade :)

**Pull request merged**
